language: [PROJECT_LANG]

services:
    - [ADD ANY SERVICES (ie docker)]

before_script:
    - [ENTER ANY SCRIPTS BEFORE EACH STAGE (SETUP MOSTLY)]

stages:
    - name: lint
    if: branch != master
    - name: test
    if: branch != master
    - name: build
    if: type = pull_request
    - name: deploy
    if: branch = master

jobs:
    allow_failures:
        - env:
            - CAN_FAIL=true
    include:
        - stage: lint
            env:
                - CAN_FAIL=true
            script:
                - [INSERT_LINT_COMMAND_HERE]
        - stage: test
            script:
                - [INSERT_TEST_COMMAND_HERE]
        - stage: build
            script:
                - ${TRAVIS_BUILD_DIR}/.travis/build.sh
        - stage: deploy
            script:
                - ${TRAVIS_BUILD_DIR}/.travis/deploy.sh
