name: Lint

on: push

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install required dev dependencies
        working-directory: "./"
        run: npm install --only=dev
      - name: Start linting
        working-directory: "./"
        run: |
          npm install lodash
          npm run lint