name: Test

on: pull_request

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dev dependencies
        run: npm install --only=dev
      - name: Run configured tests
        run: npm run test